# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

[advisories]
ignore = [
    "RUSTSEC-2026-0098",
    "RUSTSEC-2026-0099",
    "RUSTSEC-2026-0104"
]

[licenses]
confidence-threshold = 0.95
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "MIT",
    "ISC",
    "Unicode-3.0",
    "OpenSSL"
]

