[advisories]
ignore = [
    "RUSTSEC-2024-0384", # instant is no longer maintened
    "RUSTSEC-2025-0052", # async-std is no longer maintened
]

[licenses]
confidence-threshold = 0.95
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "MIT",
    "ISC",
    "Unicode-3.0"
]

