# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

[header]
text = """
Copyright {{props["inception_year"]}} {{props["copyright_owner"]}}
SPDX-License-Identifier: MIT
"""

[files]
includes = [
    "**/*.rs",
    "**/*.yml",
    "**/*.toml",
    "**/*Dockerfile",
]

[props]
inception_year = 2025
copyright_owner = "Dotanuki Labs"
